export const colorName = {
    "#CD5C5C": "IndianRed - Rojo Indio",
    "#F08080": "LightCoral - Coral Claro",
    "#FA8072": "Salmon - Salmón",
    "#E9967A": "DarkSalmon - Salmón Oscuro",
    "#FFA07A": "LightSalmon - Salmón Claro",
    "#DC143C": "Crimson - Carmesí",
    "#FF0000": "Red - Rojo",
    "#B22222": "FireBrick - Ladrillo de Fuego",
    "#8B0000": "DarkRed - Rojo Oscuro",
    "#FFC0CB": "Pink - Rosa",
    "#FFB6C1": "LightPink - Rosa Claro",
    "#FF69B4": "HotPink - Rosa Caliente",
    "#FF1493": "DeepPink - Rosa Profunda",
    "#C71585": "MediumVioletRed - Rojo Violeta Medio",
    "#DB7093": "PaleVioletRed - Rojo Violeta Pálido",
    "#FFA07A": "LightSalmon - Salmón Claro",
    "#FF7F50": "Coral - Coral",
    "#FF6347": "Tomato - Tomate",
    "#FF4500": "OrangeRed - Rojo Naranja",
    "#FF8C00": "DarkOrange - Naranja Oscuro",
    "#FFA500": "Orange - Naranja",
    "#FFD700": "Gold - Oro",
    "#FFFF00": "Yellow - Amarillo",
    "#FFFFE0": "LightYellow - Amarillo Claro",
    "#FFFACD": "LemonChiffon - Chiffon de Limón",
    "#FAFAD2": "LightGoldenrodYellow - Amarillo Dorado Claro",
    "#FFEFD5": "PapayaWhip - Batido de Papaya",
    "#FFE4B5": "Moccasin - Mocasín",
    "#FFDAB9": "PeachPuff - Melocotón",
    "#EEE8AA": "PaleGoldenrod - Dorado Pálido",
    "#F0E68C": "Khaki - Caqui",
    "#BDB76B": "DarkKhaki - Caqui Oscuro",
    "#E6E6FA": "Lavender - Lavanda",
    "#D8BFD8": "Thistle - Cardo",
    "#DDA0DD": "Plum - Ciruela",
    "#EE82EE": "Violet - Violeta",
    "#DA70D6": "Orchid - Orquídea",
    "#FF00FF": "Fuchsia - Fucsia",
    "#FF00FF": "Magenta - Magenta",
    "#BA55D3": "MediumOrchid - Orquídea Media",
    "#9370DB": "MediumPurple - Púrpura Media",
    "#9966CC": "Amethyst - Amatista",
    "#8A2BE2": "BlueViolet - Azul Violeta",
    "#9400D3": "DarkViolet - Violeta Oscuro",
    "#9932CC": "DarkOrchid - Orquídea Oscura",
    "#8B008B": "DarkMagenta - Magenta Oscuro",
    "#800080": "Purple - Púrpura",
    "#4B0082": "Indigo - Índigo",
    "#6A5ACD": "SlateBlue - Azul Pizarra",
    "#483D8B": "DarkSlateBlue - Azul Pizarra Oscuro",
    "#7B68EE": "MediumSlateBlue - Azul Pizarra Medio",
    "#4169E1": "RoyalBlue - Azul Real",
    "#0000FF": "Blue - Azul",
    "#0000CD": "MediumBlue - Azul Medio",
    "#00008B": "DarkBlue - Azul Oscuro",
    "#000080": "Navy - Azul Marino",
    "#191970": "MidnightBlue - Azul Medianoche",
    "#FFF8DC": "Cornsilk - Seda de Maíz",
    "#FFEBCD": "BlanchedAlmond - Almendra Blanqueada",
    "#FFE4C4": "Bisque - Galleta",
    "#FFDEAD": "NavajoWhite - Blanco Navajo",
    "#F5DEB3": "Wheat - Trigo",
    "#DEB887": "BurlyWood - Madera Robusta",
    "#D2B48C": "Tan - Bronceado",
    "#BC8F8F": "RosyBrown - Marrón Rosado",
    "#F4A460": "SandyBrown - Marrón Arena",
    "#DAA520": "Goldenrod - Vara de Oro",
    "#B8860B": "DarkGoldenrod - Vara de Oro Oscuro",
    "#CD853F": "Peru - Perú",
    "#D2691E": "Chocolate - Chocolate",
    "#8B4513": "SaddleBrown - Marrón Montura",
    "#A0522D": "Sienna - Siena",
    "#A52A2A": "Brown - Marrón",
    "#800000": "Maroon - Granate",
    "#FFFFFF": "White - Blanco",
    "#FFFAFA": "Snow - Nieve",
    "#F0FFF0": "Honeydew - Rocío de Miel",
    "#F5FFFA": "MintCream - Crema de Menta",
    "#F0FFFF": "Azure - Azur",
    "#F0F8FF": "AliceBlue - Azul Alicia",
    "#F8F8FF": "GhostWhite - Blanco Fantasma",
    "#F5F5F5": "WhiteSmoke - Humo Blanco",
    "#FFF5EE": "Seashell - Concha",
    "#F5F5DC": "Beige - Beige",
    "#FDF5E6": "OldLace - Encaje Antiguo",
    "#FFFAF0": "FloralWhite - Blanco Floral",
    "#FFFFF0": "Ivory - Marfil",
    "#FAEBD7": "AntiqueWhite - Blanco Antiguo",
    "#FAF0E6": "Linen - Lino",
    "#FFF0F5": "LavenderBlush - Rubor de Lavanda",
    "#FFE4E1": "MistyRose - Rosa Brumosa",
    "#DCDCDC": "Gainsboro - Gainsboro",
    "#D3D3D3": "LightGrey - Gris Claro",
    "#C0C0C0": "Silver - Plata",
    "#A9A9A9": "DarkGray - Gris Oscuro",
    "#808080": "Gray - Gris",
    "#696969": "DimGray - Gris Oscuro",
    "#778899": "LightSlateGray - Gris Pizarra Claro",
    "#708090": "SlateGray - Gris Pizarra",
    "#2F4F4F": "DarkSlateGray - Gris Pizarra Oscuro",
    "#000000": "Black - Negro",
    "#ADD8E6": "LightBlue - Azul Claro",
    "#87CEEB": "SkyBlue - Azul Cielo",
    "#87CEFA": "LightSkyBlue - Azul Cielo Claro",
    "#4682B4": "SteelBlue - Azul Acero",
    "#B0C4DE": "LightSteelBlue - Azul Acero Claro",
    "#B0E0E6": "PowderBlue - Azul Polvo",
    "#AFEEEE": "PaleTurquoise - Turquesa Pálido",
    "#00FFFF": "Aqua - Agua",
    "#00FFFF": "Cyan - Cian",
    "#00CED1": "DarkTurquoise - Turquesa Oscuro",
    "#40E0D0": "Turquoise - Turquesa",
    "#48D1CC": "MediumTurquoise - Turquesa Medio",
    "#20B2AA": "LightSeaGreen - Verde Mar Claro",
    "#008B8B": "DarkCyan - Cian Oscuro",
    "#008080": "Teal - Verde Azulado",
    "#7FFFD4": "Aquamarine - Aguamarina",
    "#66CDAA": "MediumAquamarine - Aguamarina Medio",
    "#00FA9A": "MediumSpringGreen - Verde Primavera Medio",
    "#F5FFFA": "MintCream - Crema de Menta",
    "#3CB371": "MediumSeaGreen - Verde Mar Medio",
    "#2E8B57": "SeaGreen - Verde Mar",
    "#228B22": "ForestGreen - Verde Bosque",
    "#008000": "Green - Verde",
    "#006400": "DarkGreen - Verde Oscuro",
    "#ADFF2F": "GreenYellow - Verde Amarillo",
    "#7FFF00": "Chartreuse - Cartucho",
    "#7CFC00": "LawnGreen - Verde Césped",
    "#00FF00": "Lime - Lima",
    "#32CD32": "LimeGreen - Verde Lima",
    "#98FB98": "PaleGreen - Verde Pálido",
    "#90EE90": "LightGreen - Verde Claro",
    "#00FF7F": "SpringGreen - Verde Primavera",
    "#3CB371": "MediumSeaGreen - Verde Mar Medio",
    "#2E8B57": "SeaGreen - Verde Mar",
    "#228B22": "ForestGreen - Verde Bosque",
    "#008000": "Green - Verde",
    "#006400": "DarkGreen - Verde Oscuro",
    "#9ACD32": "YellowGreen - Amarillo Verde",
    "#6B8E23": "OliveDrab - Gris Oliva",
    "#808000": "Olive - Oliva",
    "#556B2F": "DarkOliveGreen - Verde Oliva Oscuro",
    "#6B8E23": "OliveDrab - Gris Oliva",
    "#9ACD32": "YellowGreen - Amarillo Verde",
    "#32CD32": "LimeGreen - Verde Lima",
    "#BDB76B": "DarkKhaki - Caqui Oscuro",
    "#EEE8AA": "PaleGoldenrod - Dorado Pálido",
    "#00BFFF": "DeepSkyBlue - Azul Cielo Profundo",
    "#1E90FF": "DodgerBlue - Azul Dodger",
    "#6495ED": "CornflowerBlue - Azul Aciano",
    "#87CEFA": "LightSkyBlue - Azul Cielo Claro",
    "#4682B4": "SteelBlue - Azul Acero",
    "#B0C4DE": "LightSteelBlue - Azul Acero Claro",
    "#ADD8E6": "LightBlue - Azul Claro",
    "#B0E0E6": "PowderBlue - Azul Polvo",
    "#AFEEEE": "PaleTurquoise - Turquesa Pálido",
    "#00FFFF": "Aqua - Agua",
    "#00FFFF": "Cyan - Cian",
    "#00CED1": "DarkTurquoise - Turquesa Oscuro",
    "#40E0D0": "Turquoise - Turquesa",
    "#48D1CC": "MediumTurquoise - Turquesa Medio",
    "#20B2AA": "LightSeaGreen - Verde Mar Claro",
    "#008B8B": "DarkCyan - Cian Oscuro",
    "#008080": "Teal - Verde Azulado",
    "#7FFFD4": "Aquamarine - Aguamarina",
    "#66CDAA": "MediumAquamarine - Aguamarina Medio",
    "#00FA9A": "MediumSpringGreen - Verde Primavera Medio",
    "#F5FFFA": "MintCream - Crema de Menta",
    "#3CB371": "MediumSeaGreen - Verde Mar Medio",
    "#2E8B57": "SeaGreen - Verde Mar",
    "#228B22": "ForestGreen - Verde Bosque",
    "#008000": "Green - Verde",
    "#006400": "DarkGreen - Verde Oscuro",
    "#ADFF2F": "GreenYellow - Verde Amarillo",
    "#7FFF00": "Chartreuse - Cartucho",
    "#7CFC00": "LawnGreen - Verde Césped",
    "#00FF00": "Lime - Lima",
    "#32CD32": "LimeGreen - Verde Lima",
    "#98FB98": "PaleGreen - Verde Pálido",
    "#90EE90": "LightGreen - Verde Claro",
    "#00FF7F": "SpringGreen - Verde Primavera",
    "#3CB371": "MediumSeaGreen - Verde Mar Medio",
    "#2E8B57": "SeaGreen - Verde Mar",
    "#228B22": "ForestGreen - Verde Bosque",
    "#008000": "Green - Verde",
    "#006400": "DarkGreen - Verde Oscuro",
    "#9ACD32": "YellowGreen - Amarillo Verde",
    "#6B8E23": "OliveDrab - Gris Oliva",
    "#808000": "Olive - Oliva",
    "#556B2F": "DarkOliveGreen - Verde Oliva Oscuro",
    "#6B8E23": "OliveDrab - Gris Oliva",
    "#9ACD32": "YellowGreen - Amarillo Verde",
    "#32CD32": "LimeGreen - Verde Lima",
    "#BDB76B": "DarkKhaki - Caqui Oscuro",
    "#EEE8AA": "PaleGoldenrod - Dorado Pálido",
    "#8FBC8F": "DarkSeaGreen - Verde Mar Oscuro",
    "#66CDAA": "MediumAquamarine - Aguamarina Medio",
    "#7FFFD4": "Aquamarine - Aguamarina",
    "#006400": "DarkGreen - Verde Oscuro",
    "#556B2F": "DarkOliveGreen - Verde Oliva Oscuro",
    "#8B4513": "SaddleBrown - Marrón Montura",
    "#A0522D": "Sienna - Siena",
    "#CD853F": "Peru - Perú",
    "#DEB887": "BurlyWood - Madera Robusta",
    "#D2B48C": "Tan - Bronceado",
    "#BC8F8F": "RosyBrown - Marrón Rosado",
    "#F4A460": "SandyBrown - Marrón Arena",
    "#DAA520": "Goldenrod - Vara de Oro",
    "#B8860B": "DarkGoldenrod - Vara de Oro Oscuro",
    "#CD5C5C": "IndianRed - Rojo Indio",
    "#8B4513": "SaddleBrown - Marrón Montura",
    "#A0522D": "Sienna - Siena",
    "#CD853F": "Peru - Perú",
    "#DEB887": "BurlyWood - Madera Robusta",
    "#D2B48C": "Tan - Bronceado",
    "#BC8F8F": "RosyBrown - Marrón Rosado",
    "#F4A460": "SandyBrown - Marrón Arena",
    "#DAA520": "Goldenrod - Vara de Oro",
    "#B8860B": "DarkGoldenrod - Vara de Oro Oscuro",
    "#CD5C5C": "IndianRed - Rojo Indio",
    "#8B4513": "SaddleBrown - Marrón Montura",
    "#A0522D": "Sienna - Siena",
    "#CD853F": "Peru - Perú",
    "#DEB887": "BurlyWood - Madera Robusta",
    "#D2B48C": "Tan - Bronceado",
    "#BC8F8F": "RosyBrown - Marrón Rosado",
    "#F4A460": "SandyBrown - Marrón Arena",
    "#DAA520": "Goldenrod - Vara de Oro",
    "#B8860B": "DarkGoldenrod - Vara de Oro Oscuro",
    "#CD5C5C": "IndianRed - Rojo Indio",
    "#7FFF00": "Chartreuse - Cartucho",
    "#D2691E": "Chocolate - Chocolate",
    "#FF7F50": "Coral - Coral",
    "#6495ED": "CornflowerBlue - Azul Aciano",
    "#FFF8DC": "Cornsilk - Seda de Maíz",
    "#DC143C": "Crimson - Carmesí",
    "#00008B": "DarkBlue - Azul Oscuro",
    "#008B8B": "DarkCyan - Cian Oscuro",
    "#B8860B": "DarkGoldenrod - Vara de Oro Oscuro",
    "#A9A9A9": "DarkGray - Gris Oscuro",
    "#006400": "DarkGreen - Verde Oscuro",
    "#BDB76B": "DarkKhaki - Caqui Oscuro",
    "#8B008B": "DarkMagenta - Magenta Oscuro",
    "#556B2F": "DarkOliveGreen - Verde Oliva Oscuro",
    "#FF8C00": "DarkOrange - Naranja Oscuro",
    "#9932CC": "DarkOrchid - Orquídea Oscura",
    "#8B0000": "DarkRed - Rojo Oscuro",
    "#E9967A": "DarkSalmon - Salmón Oscuro",
    "#8FBC8F": "DarkSeaGreen - Verde Mar Oscuro",
    "#483D8B": "DarkSlateBlue - Azul Pizarra Oscuro",
    "#2F4F4F": "DarkSlateGray - Gris Pizarra Oscuro",
    "#00CED1": "DarkTurquoise - Turquesa Oscuro",
    "#9400D3": "DarkViolet - Violeta Oscuro",
    "#FF1493": "DeepPink - Rosa Profunda",
    "#00BFFF": "DeepSkyBlue - Azul Cielo Profundo",
    "#696969": "DimGray - Gris Oscuro",
    "#1E90FF": "DodgerBlue - Azul Dodger",
    "#B22222": "FireBrick - Ladrillo de Fuego",
    "#FFFAF0": "FloralWhite - Blanco Floral",
    "#228B22": "ForestGreen - Verde Bosque",
    "#FF00FF": "Fuchsia - Fucsia",
    "#DCDCDC": "Gainsboro - Gainsboro",
    "#F8F8FF": "GhostWhite - Blanco Fantasma",
    "#FFD700": "Gold - Oro",
    "#DAA520": "Goldenrod - Vara de Oro",
    "#808080": "Gray - Gris",
    "#008000": "Green - Verde",
    "#ADFF2F": "GreenYellow - Verde Amarillo",
    "#F0FFF0": "Honeydew - Rocío de Miel",
    "#FF69B4": "HotPink - Rosa Caliente",
    "#CD5C5C": "IndianRed - Rojo Indio",
    "#4B0082": "Indigo - Índigo",
    "#FFFFF0": "Ivory - Marfil",
    "#F0E68C": "Khaki - Caqui",
    "#E6E6FA": "Lavender - Lavanda",
    "#FFF0F5": "LavenderBlush - Rubor de Lavanda",
    "#7CFC00": "LawnGreen - Verde Césped",
    "#FFFACD": "LemonChiffon - Chiffon de Limón",
    "#ADD8E6": "LightBlue - Azul Claro",
    "#F08080": "LightCoral - Coral Claro",
    "#E0FFFF": "LightCyan - Cian Claro",
    "#FAFAD2": "LightGoldenrodYellow - Amarillo Dorado Claro",
    "#D3D3D3": "LightGray - Gris Claro",
    "#90EE90": "LightGreen - Verde Claro",
    "#FFB6C1": "LightPink - Rosa Claro",
    "#FFA07A": "LightSalmon - Salmón Claro",
    "#20B2AA": "LightSeaGreen - Verde Mar Claro",
    "#87CEFA": "LightSkyBlue - Azul Cielo Claro",
    "#778899": "LightSlateGray - Gris Pizarra Claro",
    "#B0C4DE": "LightSteelBlue - Azul Acero Claro",
    "#FFFFE0": "LightYellow - Amarillo Claro",
    "#00FF00": "Lime - Lima",
    "#32CD32": "LimeGreen - Verde Lima",
    "#FAF0E6": "Linen - Lino",
    "#FF00FF": "Magenta - Magenta",
    "#800000": "Maroon - Granate",
    "#66CDAA": "MediumAquamarine - Aguamarina Medio",
    "#0000CD": "MediumBlue - Azul Medio",
    "#BA55D3": "MediumOrchid - Orquídea Media",
    "#9370DB": "MediumPurple - Púrpura Media",
    "#3CB371": "MediumSeaGreen - Verde Mar Medio",
    "#7B68EE": "MediumSlateBlue - Azul Pizarra Medio",
    "#00FA9A": "MediumSpringGreen - Verde Primavera Medio",
    "#48D1CC": "MediumTurquoise - Turquesa Medio",
    "#C71585": "MediumVioletRed - Rojo Violeta Medio",
    "#191970": "MidnightBlue - Azul Medianoche",
    "#F5FFFA": "MintCream - Crema de Menta",
    "#FFE4E1": "MistyRose - Rosa Brumosa",
    "#FFE4B5": "Moccasin - Mocasín",
    "#FFDEAD": "NavajoWhite - Blanco Navajo",
    "#000080": "Navy - Azul Marino",
    "#FDF5E6": "OldLace - Encaje Antiguo",
    "#808000": "Olive - Oliva",
    "#6B8E23": "OliveDrab - Gris Oliva",
    "#FFA500": "Orange - Naranja",
    "#FF4500": "OrangeRed - Rojo Naranja",
    "#DA70D6": "Orchid - Orquídea",
    "#EEE8AA": "PaleGoldenrod - Dorado Pálido",
    "#98FB98": "PaleGreen - Verde Pálido",
    "#AFEEEE": "PaleTurquoise - Turquesa Pálido",
    "#DB7093": "PaleVioletRed - Rojo Violeta Pálido",
    "#FFEFD5": "PapayaWhip - Batido de Papaya",
    "#FFDAB9": "PeachPuff - Melocotón",
    "#CD853F": "Peru - Perú",
    "#FFC0CB": "Pink - Rosa",
    "#DDA0DD": "Plum - Ciruela",
    "#B0E0E6": "PowderBlue - Azul Polvo",
    "#800080": "Purple - Púrpura",
    "#FF0000": "Red - Rojo",
    "#BC8F8F": "RosyBrown - Marrón Rosado",
    "#4169E1": "RoyalBlue - Azul Real",
    "#8B4513": "SaddleBrown - Marrón Montura",
    "#FA8072": "Salmon - Salmón",
    "#F4A460": "SandyBrown - Marrón Arena",
    "#2E8B57": "SeaGreen - Verde Mar",
    "#FFF5EE": "Seashell - Concha",
    "#A0522D": "Sienna - Siena",
    "#C0C0C0": "Silver - Plata",
    "#87CEEB": "SkyBlue - Azul Cielo",
    "#6A5ACD": "SlateBlue - Azul Pizarra",
    "#708090": "SlateGray - Gris Pizarra",
    "#FFFAFA": "Snow - Nieve",
    "#00FF7F": "SpringGreen - Verde Primavera",
    "#4682B4": "SteelBlue - Azul Acero",
    "#D2B48C": "Tan - Bronceado",
    "#008080": "Teal - Verde Azulado",
    "#D8BFD8": "Thistle - Cardo",
    "#FF6347": "Tomato - Tomate",
    "#40E0D0": "Turquoise - Turquesa",
    "#EE82EE": "Violet - Violeta",
    "#F5DEB3": "Wheat - Trigo",
    "#FFFFFF": "White - Blanco",
    "#F5F5F5": "WhiteSmoke - Humo Blanco",
    "#FFFF00": "Yellow - Amarillo",
    "#9ACD32": "YellowGreen - Amarillo Verde",
};
